import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import StoreProvider from "~/lib/providers/store-provider";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <ClerkProvider>
            <StoreProvider>
                <html lang="en" className={`${GeistSans.variable} dark`}>
                    <body>
                        <div className="absolute right-4 top-8">
                            <SignedIn>
                                <UserButton />
                            </SignedIn>
                        </div>

                        {children}
                    </body>
                </html>
            </StoreProvider>
        </ClerkProvider>
    );
}
